name: whatsapp-baileys
services:
  - type: app
    name: whatsapp-baileys-app
    source:
      type: dockerfile
    build:
      dockerfile: Dockerfile
    ports:
      - port: 3000
        protocol: http
      - port: 3001
        protocol: http
    env:
      - key: NODE_ENV
        value: production
    volumes:
      - type: directory
        path: /app/auth_info_baileys
        name: whatsapp-auth

